[project]
name = "undergrad-computational-macro"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ipython>=9.1.0",
    "jupyter>=1.1.1",
    "jupyter-cache>=1.0.1",
    "nbconvert>=7.16.6",
    "ruff>=0.11.4",
]
